name: expance_tracker
description: "A new Flutter project."
version: 1.0.2+2

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.3.0
  get: ^4.6.6
  http: ^1.2.2
  csv: ^6.0.0
  lottie: ^3.1.2
  country_flags: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_mobile_ads: ^5.1.0
  firebase_core: ^3.5.0
  firebase_remote_config: ^5.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/animations/
